import { Produto } from "@/model/produtos";
import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Produto[]>
) {
  return res.json([
    {
      id: 1,
      name: "Arroz Branco",
      description: "Pacote de 5kg de arroz branco.",
      price: 29.9,
      category: "Grãos",
      inStock: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: "Feijão Preto",
      description: "Feijão preto de alta qualidade 1kg.",
      price: 8.5,
      category: "Grãos",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      name: "Macarrão Espaguete",
      description: "Macarrão tipo espaguete 500g.",
      price: 4.99,
      category: "Massas",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      name: "Óleo de Soja",
      description: "Garrafa de 900ml de óleo de soja.",
      price: 7.3,
      category: "Óleos e Gorduras",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      name: "Açúcar Refinado",
      description: "Pacote de 1kg de açúcar refinado.",
      price: 3.75,
      category: "Açúcar",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      name: "Farinha de Trigo",
      description: "Pacote de 1kg de farinha de trigo.",
      price: 5.8,
      category: "Farinhas",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 7,
      name: "Leite Integral",
      description: "Caixa de 1L de leite integral.",
      price: 4.1,
      category: "Laticínios",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 8,
      name: "Queijo Mussarela",
      description: "Queijo mussarela fatiado 200g.",
      price: 15.9,
      category: "Laticínios",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 9,
      name: "Café Tradicional",
      description: "Pacote de 500g de café moído tradicional.",
      price: 12.5,
      category: "Bebidas",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 10,
      name: "Refrigerante Cola",
      description: "Garrafa de 2L de refrigerante de cola.",
      price: 7.9,
      category: "Bebidas",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 11,
      name: "Papel Higiênico",
      description: "Pacote com 12 rolos de papel higiênico.",
      price: 16.9,
      category: "Higiene Pessoal",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 12,
      name: "Sabonete Líquido",
      description: "Frasco de 500ml de sabonete líquido.",
      price: 10.9,
      category: "Higiene Pessoal",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 13,
      name: "Desinfetante Floral",
      description: "Frasco de 1L de desinfetante com aroma floral.",
      price: 6.5,
      category: "Limpeza",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 14,
      name: "Detergente Neutro",
      description: "Frasco de 500ml de detergente líquido neutro.",
      price: 3.8,
      category: "Limpeza",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 15,
      name: "Shampoo",
      description: "Frasco de 400ml de shampoo para cabelos normais.",
      price: 18.9,
      category: "Higiene Pessoal",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 16,
      name: "Condicionador",
      description: "Frasco de 400ml de condicionador hidratante.",
      price: 19.5,
      category: "Higiene Pessoal",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 17,
      name: "Sabão em Pó",
      description: "Pacote de 1kg de sabão em pó para roupas.",
      price: 12.9,
      category: "Limpeza",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 18,
      name: "Água Mineral",
      description: "Garrafa de 1.5L de água mineral sem gás.",
      price: 2.99,
      category: "Bebidas",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 19,
      name: "Cereal Matinal",
      description: "Caixa de 300g de cereal matinal.",
      price: 8.7,
      category: "Cereais",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 20,
      name: "Chocolate ao Leite",
      description: "Barra de chocolate ao leite 90g.",
      price: 4.5,
      category: "Confeitaria",
      inStock: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
}
